Proiect-ASP_Final/Proiect-ASP-main/Proiect-ASP/CrowdKnowledgeContribution/CrowdKnowledgeContribution/Models/ArticleHistory.cs
using CrowdKnowledgeContribution.Data;
using Microsoft.AspNetCore.Mvc.ApplicationModels;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CrowdKnowledgeContribution.Models
{
    public class ArticleHistory
    {
       // [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int Id { get; set; }
        public DateTime Date { get; set; }

        [Required(ErrorMessage = "Titlul este obligatoriu")]
        [StringLength(100, ErrorMessage = "Titlul nu poate avea mai mult de 100 de caractere")]
        [MinLength(5, ErrorMessage = "Titlul trebuie sa aiba mai mult de 5 caractere")]
        public string Title { get; set; }

        [Required(ErrorMessage = "Continutul articolului este obligatoriu")]
        public string Content { get; set; }

        [Required(ErrorMessage = "Categoria este obligatorie")]
        public int? CategoryId { get; set; }

        public string? UserId { get; set; }

        public virtual ApplicationUser? User { get; set; }

        public virtual Category? Category { get; set; }

        public virtual ProtectedArticle? ProtectedArticle { get; set; }

        public virtual ICollection<Comment>? Comments { get; set; }

        [NotMapped]
        public IEnumerable<SelectListItem>? Categ { get; set; }

    }
}

Proiect-ASP_Final/Proiect-ASP-main/Proiect-ASP/CrowdKnowledgeContribution/CrowdKnowledgeContribution/Controllers/ArticleHistoryController.cs
using CrowdKnowledgeContribution.Data;
using CrowdKnowledgeContribution.Models;
using Ganss.XSS;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Data;


namespace CrowdKnowledgeContribution.Controllers
{
    [Authorize(Roles="Admin")]
    public class ArticleHistoryController : Controller
    {
        

        private readonly ApplicationDbContext db;
        
        public ArticleHistoryController(ApplicationDbContext context)
        {
            db = context;
        }

        public IActionResult Index(int id)
        {
            List<ArticleHistory> article_versions = db.ArticleHistories.Include("Category")
                                                                      .Include("User")
                                                                      .Include("Comments")
                                                                      .Include("Comments.User")
                                                                      .Where(art => art.Id == id)
                                                                      .OrderByDescending(art => art.Date)
                                                                      .ToList();
            ViewBag.Istoric = article_versions;
            return View();
        }

        public IActionResult UpdateArticle(int id, DateTime date)
        {
            List<ArticleHistory> article_versions = db.ArticleHistories.Include("Category")
                                                                .Include("User")
                                                                .Include("Comments")
                                                                .Include("Comments.User")
                                                                .Where(art => art.Id == id)
                                                                .ToList();

            

            Article article = db.Articles.Include("Category")
                                         .Include("User")
                                         .Include("Comments")
                                         .Include("Comments.User")
                                         .Where(art => art.Id == id)
                                         .First();



            ///{1/7/2023 1:44:51 PM}
            ///{1/7/2023 4:19:51 PM}
            ///{1/7/2023 10:54:21 PM}

            int nr = 0;

            foreach (ArticleHistory art in article_versions)
            {
                nr++;

                var ok = art.Date.Equals(date);

                if(date.Date == art.Date.Date && date.Hour == art.Date.Hour && date.Minute == art.Date.Minute && date.Second == art.Date.Second)
                {
                    
                    article.Title = art.Title;
                    article.Content = art.Content;
                    article.Date = date;
                    article.CategoryId = art.CategoryId;
                    article.Comments = art.Comments;
                    article.User = art.User;
                    article.UserId = art.UserId;
                    article.Categ = art.Categ;

                    db.SaveChanges();
                }
                
            }

            return View(article);

        }
    }
}

Proiect-ASP_Final/Proiect-ASP-main/Proiect-ASP/CrowdKnowledgeContribution/CrowdKnowledgeContribution/Views/ArticleHistory/Index.cshtml
@model CrowdKnowledgeContribution.Models.ArticleHistory


<table class="table">
    <thead class="text-center">
        <tr>
            <th>TITLU</th>
            <th width="40%">CONTINUT</th>
            <th>DATA</th>
            <th>CATEGORIE</th>
            <th>ACTIUNE</th>

        </tr>
    </thead>
    <tbody>
        @foreach (CrowdKnowledgeContribution.Models.ArticleHistory article in ViewBag.Istoric)
        {

            <tr>
                <th class="text-center">@article.Title</th>
                <th>@Html.Raw(@article.Content)</th>
                <th class="text-center">@article.Date</th>
                <th class="text-center">@article.Category.CategoryName</th>

                <th>
                    <button class="btn search" type="submit">@Html.ActionLink("Update", "UpdateArticle", "ArticleHistory", new{id = article.Id, date = article.Date}, new{style = "text-decoration:none; color: white"})</button>
                </th>

            </tr>



        }

    </tbody>
</table>

Proiect-ASP_Final/Proiect-ASP-main/Proiect-ASP/CrowdKnowledgeContribution/CrowdKnowledgeContribution/Views/ArticleHistory/UpdateArticle.cshtml
@model CrowdKnowledgeContribution.Models.Article

<br />

<div class="card">

    @Html.Partial("ArticleInfo", Model)
</div>

<br />
<br />

@foreach (var comm in Model.Comments)
{
    <div class="container">
        <div class="row">
            <div class="col-md-2"></div>

            <div class="col-md-8">

                <div>

                    <p>@comm.Content</p>
                    <small>@comm.Date</small>
                    <strong><i class="bi bi-person"></i>@comm.User.UserName</strong>

                </div>
                <br>

                @if (comm.UserId == ViewBag.UserCurent || ViewBag.EsteAdmin)
                {

                    <div class="d-flex">

                        <div>

                            <a class="btn btn-outline-success" href="/Comments/Edit/@comm.Id"><i class="bi bi-vector-pen"></i>Editeaza</a>

                        </div>

                        <div>

                            <form method="post" action="/Comments/Delete/@comm.Id">

                                <button class="btn btn-outline-danger" type="submit"><i class="bi bi-trash"></i>Sterge</button>

                            </form>

                        </div>

                    </div>
                }

                <br />

            </div>

            <div class="col-md-2"></div>

        </div>

    </div>
}

<div class="container">

    <div class="row">

        <div class="col-md-2"></div>

        <div class="col-md-8">

            <div class="card">

                <form method="post" action="/Articles/Show/@Model.Id">

                    <div class="card-body">

                        <input type="hidden" name="ArticleId" value="@Model.Id" />

                        <label>Continut comentariu</label>
                        <br />

                        <textarea class="form-control" name="Content"></textarea>

                        @Html.ValidationMessage("Content", null, new { @class = "text-danger"})

                        <br /><br />

                        <button class="btn alert-success " type="submit">Adauga comentariul</button>

                    </div>

                </form>

            </div>

        </div>

        <div class="col-md-2"></div>

    </div>

</div>