Proiect-ASP_Final/Proiect-ASP-main/Proiect-ASP/CrowdKnowledgeContribution/CrowdKnowledgeContribution/Controllers/ArticlesController.cs
using CrowdKnowledgeContribution.Data;
using CrowdKnowledgeContribution.Models;
using Ganss.XSS;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Data;

namespace CrowdKnowledgeContribution.Controllers
{
    [Authorize]
    public class ArticlesController : Controller
    {
        private readonly ApplicationDbContext db;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        public ArticlesController(
        ApplicationDbContext context,
        UserManager<ApplicationUser> userManager,
        RoleManager<IdentityRole> roleManager
        )
        {
            db = context;
            _userManager = userManager;
            _roleManager = roleManager;
        }

        [Authorize(Roles = "Editor interzis,Editor,Admin")]
        public IActionResult Index()
        {
            var articles = db.Articles.Include("Category").Include("User").OrderBy(a => a.Date);

            var search = "";

            if (Convert.ToString(HttpContext.Request.Query["search"]) != null)
            {
                search = Convert.ToString(HttpContext.Request.Query["search"]).Trim();

                List<int> articleIds = db.Articles.Where
                                        (
                                        at => at.Title.Contains(search)
                                        || at.Content.Contains(search)
                                        ).Select(a => a.Id).ToList();

                List<int> articleIdsOfCommentsWithSearchString = db.Comments.Where
                                        (
                                        c => c.Content.Contains(search)
                                        ).Select(c => (int)c.ArticleId).ToList();

                List<int> mergedIds = articleIds.Union(articleIdsOfCommentsWithSearchString).ToList();

                articles = db.Articles.Where(article => mergedIds.Contains(article.Id))
                            .Include("Category")
                            .Include("User")
                            .OrderBy(a => a.Date);
            }

            ViewBag.SearchString = search;

            ViewBag.Articles = articles;

            int _perPage = 4;

            if (TempData.ContainsKey("message"))
            {
                ViewBag.message = TempData["message"].ToString();
            }

            int totalItems = articles.Count();

            var currentPage = Convert.ToInt32(HttpContext.Request.Query["page"]);

            var offset = 0;

            if (!currentPage.Equals(0))
            {
                offset = (currentPage - 1) * _perPage;
            }

            var paginatedArticles = articles.Skip(offset).Take(_perPage);

            ViewBag.lastPage = Math.Ceiling((float)totalItems / (float)_perPage);

            ViewBag.Articles = paginatedArticles;

            if (search != "")
            {
                ViewBag.PaginationBaseUrl = "/Articles/Index/?search=" + search + "&page";
            }
            else
            {
                ViewBag.PaginationBaseUrl = "/Articles/Index/?page";
            }

            return View();
        }

        private void SetAccessRights()
        {
            ViewBag.AfisareButoane = false;

            if (User.IsInRole("Editor"))
            {
                ViewBag.AfisareButoane = true;
            }

            ViewBag.UserCurent = _userManager.GetUserId(User);

            ViewBag.EsteAdmin = User.IsInRole("Admin");
        }

        private void SetAccessForArticleHistory()
        {
            ViewBag.VersionControl = false;

            if(User.IsInRole("Admin"))
            {
                ViewBag.VersionControl = true;
            }
        }

        [Authorize(Roles = "Editor interzis,Editor,Admin")]
        public IActionResult Show(int id)
        {
            Article article = db.Articles.Include("Category")
                                         .Include("User")
                                         .Include("Comments")
                                         .Include("Comments.User")
                                         .Where(art => art.Id == id)
                                         .First();

            SetAccessRights();

            SetAccessForArticleHistory();

            SetProtectUnProtect(id);

            return View(article);
        }

        [HttpPost]
        public IActionResult Show([FromForm] Comment comment)
        {
            comment.Date = DateTime.Now;
            comment.UserId = _userManager.GetUserId(User);

            if (ModelState.IsValid)
            {
                db.Comments.Add(comment);
                db.SaveChanges();
                return Redirect("/Articles/Show/" + comment.ArticleId);
            }

            else
            {
                Article art = db.Articles.Include("Category")
                                         .Include("User")
                                         .Include("Comments")
                                         .Include("Comments.User")
                                         .Where(art => art.Id == comment.ArticleId)
                                         .First();

                SetAccessRights();

                SetAccessForArticleHistory();

                return View(art);
            }
        }

        [Authorize(Roles = "Editor,Admin")]
        public IActionResult New()
        {
            Article article = new Article();
            article.Categ = GetAllCategories();

            return View(article);
        }

        [HttpPost]
        [Authorize(Roles = "Editor,Admin")]
        public IActionResult New(Article article)
        {
            var sanitizer = new HtmlSanitizer();

            
            article.Date = DateTime.Now;
            article.UserId = _userManager.GetUserId(User);

           

            if (ModelState.IsValid)
            {
                article.Content = sanitizer.Sanitize(article.Content);
                db.Articles.Add(article);
                db.SaveChanges();

                ArticleHistory articleHistory = new ArticleHistory();

                articleHistory.Id = article.Id;
                articleHistory.Content = article.Content;
                articleHistory.Title = article.Title;
                articleHistory.Date = DateTime.Now;
                articleHistory.UserId = _userManager.GetUserId(User);
                articleHistory.CategoryId = article.CategoryId;

                db.ArticleHistories.Add(articleHistory);
                db.SaveChanges();

                TempData["message"] = "Articolul a fost adaugat.";
                return RedirectToAction("Index");

            }
            else
            {
                article.Categ = GetAllCategories();
                return View(article);
            }

        }

        [Authorize(Roles = "Editor,Admin")]
        public IActionResult Edit(int id)
        {

            SetProtectUnProtect(id);



            Article article = db.Articles.Include("Category")
                                        .Where(art => art.Id == id)
                                        .First();

            article.Categ = GetAllCategories();

            if ((article.UserId == _userManager.GetUserId(User) && ViewBag.AfisareProtect == true) || User.IsInRole("Admin"))
            {
                return View(article);
            }
            else if (article.UserId != _userManager.GetUserId(User) && !User.IsInRole("Admin"))
                TempData["message"] = "Nu aveti dreptul sa faceti modificari asupra unui articol care nu va apartine.";
            else if (ViewBag.AfisareProtect == false)
                TempData["message"] = "Nu aveti dreptul sa faceti modificari asupra unui articol care este arhivat.";
            return RedirectToAction("Index");
        }

        [HttpPost]
        [Authorize(Roles = "Editor,Admin")]
        public IActionResult Edit(int id, Article requestArticle)
        {
            var sanitizer = new HtmlSanitizer();
            SetProtectUnProtect(id);

            Article article = db.Articles.Find(id);

            if (ModelState.IsValid)
            {
                if ((article.UserId == _userManager.GetUserId(User) && ViewBag.AfisareProtect == true) || User.IsInRole("Admin"))
                {
                    article.Title = requestArticle.Title;
                    requestArticle.Content = sanitizer.Sanitize(requestArticle.Content);
                    article.Content = requestArticle.Content;
                    article.CategoryId = requestArticle.CategoryId;
                    article.Id = requestArticle.Id;
                    article.UserId = _userManager.GetUserId(User);


                    ArticleHistory articleHistory = new ArticleHistory();

                    articleHistory.Title = article.Title;
                    articleHistory.Id = article.Id;
                    articleHistory.Date = DateTime.Now;
                    articleHistory.UserId = _userManager.GetUserId(User);
                    articleHistory.CategoryId = article.CategoryId;
                    articleHistory.Content = article.Content;


                    db.ArticleHistories.Add(articleHistory);


                    TempData["message"] = "Articolul a fost modificat.";
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else if (article.UserId != _userManager.GetUserId(User) && !User.IsInRole("Admin"))
                    TempData["message"] = "Nu aveti dreptul sa faceti modificari asupra unui articol care nu va apartine.";
                else if (ViewBag.AfisareProtect == false)

Proiect-ASP_Final/Proiect-ASP-main/Proiect-ASP/CrowdKnowledgeContribution/CrowdKnowledgeContribution/Controllers/UsersController.cs
using CrowdKnowledgeContribution.Data;
using CrowdKnowledgeContribution.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Drawing.Printing;

namespace CrowdKnowledgeContribution.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersController : Controller
    {
        private readonly ApplicationDbContext db;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        public UsersController(
        ApplicationDbContext context,
        UserManager<ApplicationUser> userManager,
        RoleManager<IdentityRole> roleManager
        )
        {
            db = context;
            _userManager = userManager;
            _roleManager = roleManager;
        }
        public ActionResult Index()
        {
            if (TempData.ContainsKey("message"))
            {
                ViewBag.message = TempData["message"].ToString();
            }

            var users = from user in db.Users
                        orderby user.UserName
                        select user;
            ViewBag.Users = users;
            return View();
        }

        public async Task<ActionResult> Show(string id)
        {
            ApplicationUser user = db.Users.Find(id);
            var roleNames = await _userManager.GetRolesAsync(user);

            var currentUserRole = _roleManager.Roles
                                              .Where(r => roleNames.Contains(r.Name))
                                              .Select(r => r.Name)
                                              .First();
            SetBlockUnBlock(currentUserRole);
            return View(user);
        }

        [NonAction]
        public IEnumerable<SelectListItem> GetAllRoles()
        {
            var selectList = new List<SelectListItem>();

            var roles = from role in db.Roles
                        select role;

            foreach (var role in roles)
            {
                selectList.Add(new SelectListItem
                {
                    Value = role.Id.ToString(),
                    Text = role.Name.ToString()
                });
            }
            return selectList;
        }

        public ActionResult New()
        {
            ApplicationUser user = new ApplicationUser();

            user.AllRoles = GetAllRoles();

            return View(user);
        }

        [HttpPost]
        public async Task<ActionResult> New(ApplicationUser user, [FromForm] string role)
        {
            if (ModelState.IsValid)
            {
                user.NormalizedUserName = user.UserName.ToUpper();
                user.NormalizedEmail = user.Email.ToUpper();
                var hasher = new PasswordHasher<ApplicationUser>();
                user.PasswordHash = hasher.HashPassword(null, user.PasswordHash);
                user.EmailConfirmed = true;
                db.Users.Add(user);
                db.SaveChanges();

                var roleName = await _roleManager.FindByIdAsync(role);
                await _userManager.AddToRoleAsync(user, roleName.ToString());

                TempData["message"] = "Utilizatorul a fost adaugat.";
                return RedirectToAction("Index");
            }

            else
            {
                user.AllRoles = GetAllRoles();
                return View(user);
            }
        }
        public async Task<ActionResult> Edit(string id)
        {
            ApplicationUser user = db.Users.Find(id);

            user.AllRoles = GetAllRoles();

            var roleNames = await _userManager.GetRolesAsync(user);

            var currentUserRole = _roleManager.Roles
                                              .Where(r => roleNames.Contains(r.Name))
                                              .Select(r => r.Id)
                                              .First();
            ViewBag.UserRole = currentUserRole;

            return View(user);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(string id, ApplicationUser newData, [FromForm] string newRole)
        {
            ApplicationUser user = db.Users.Find(id);

            user.AllRoles = GetAllRoles();


            if (ModelState.IsValid)
            {
                user.UserName = newData.UserName;
                user.Email = newData.Email;
                user.FirstName = newData.FirstName;
                user.LastName = newData.LastName;
                user.PhoneNumber = newData.PhoneNumber;

                var roles = db.Roles.ToList();

                foreach (var role in roles)
                    await _userManager.RemoveFromRoleAsync(user, role.Name);
         
                var roleName = await _roleManager.FindByIdAsync(newRole);
                await _userManager.AddToRoleAsync(user, roleName.ToString());

                db.SaveChanges();
                TempData["message"] = "Au fost modificate datele utilizatorului.";
            }
            
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Delete(string id)
        {
            ApplicationUser user = db.Users.Find(id);
            db.Users.Remove(user);
            TempData["message"] = "Utilizatorul a fost eliminat.";
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        private void SetBlockUnBlock(string role)
        {
            ViewBag.AfisareBlock = false;
            ViewBag.AfisareUnBlock = false;
            if (role == "Editor")
            {
                ViewBag.AfisareBlock = true;
            }
            else if (role == "Editor interzis")
            {
                ViewBag.AfisareUnBlock = true;
            }
        }

        [HttpPost]
        public async Task<ActionResult> Block(string id)
        {

            ApplicationUser user = db.Users.Find(id);
            var roleNames = await _userManager.GetRolesAsync(user);

            var currentUserRole = _roleManager.Roles
                                              .Where(r => roleNames.Contains(r.Name))
                                              .Select(r => r.Name)
                                              .First();
            
            if (currentUserRole.ToString() == "Editor")
            {
                TempData["message"] = "Utilizatorul a fost blocat.";
                await _userManager.RemoveFromRoleAsync(user, "Editor");
                await _userManager.AddToRoleAsync(user, "Editor interzis");
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<ActionResult> UnBlock(string id)
        {

            ApplicationUser user = db.Users.Find(id);
            var roleNames = await _userManager.GetRolesAsync(user);

            var currentUserRole = _roleManager.Roles
                                              .Where(r => roleNames.Contains(r.Name))
                                              .Select(r => r.Name)
                                              .First();
            if (currentUserRole.ToString() == "Editor interzis")
            {
                TempData["message"] = "Utilizatorul a fost deblocat.";
                await _userManager.RemoveFromRoleAsync(user, "Editor interzis");
                await _userManager.AddToRoleAsync(user, "Editor");
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

    }
}

Proiect-ASP_Final/Proiect-ASP-main/Proiect-ASP/CrowdKnowledgeContribution/CrowdKnowledgeContribution/Views/Shared/ArticleHistory.cshtml
<div class="card-body">

    <h3 class="card-title alert-secondary py-3 px-3 rounded-2">@Model.Title</h3>

    <div class="card-text">@Html.Raw(@Model.Content)</div>

    <div class="d-flex justify-content-between flex-row mt-5">

        <div><i class="bi bi-bookmark"></i>@Model.Category.CategoryName</div>

        <div><i class="bi bi-person"></i>@Model.User.UserName</div>

        <span class="alert-primary"><i class="bi bi-calendar"></i>@Model.Date</span>

    </div>

</div>

Proiect-ASP_Final/Proiect-ASP-main/Proiect-ASP/CrowdKnowledgeContribution/CrowdKnowledgeContribution/Views/Shared/ArticleInfo.cshtml
<div class="card-body">

    <h3 class="card-title alert-secondary py-3 px-3 rounded-2">@Model.Title</h3>

    <div class="card-text">@Html.Raw(@Model.Content)</div>

    <div class="d-flex justify-content-between flex-row mt-5">

        <div><i class="bi bi-bookmark"></i>@Model.Category.CategoryName</div>

        <div><i class="bi bi-person"></i>@Model.User.UserName</div>

        <span class="alert-primary"><i class="bi bi-calendar"></i>@Model.Date</span>

    </div>

</div>

Proiect-ASP_Final/Proiect-ASP-main/Proiect-ASP/CrowdKnowledgeContribution/CrowdKnowledgeContribution/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CrowdKnowledgeContribution</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CrowdKnowledgeContribution.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.1/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.css" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CrowdKnowledgeContribution</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 justify-content-center">
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Acasa</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Articles" asp-action="Index">Articole</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Articles" asp-action="New">Adaugare articol</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Categorii</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Utilizatori</a>
                            </li>
                        }
                        @if (User.IsInRole("Editor"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Acasa</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Articles" asp-action="Index">Articole</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Articles" asp-action="New">Adaugare articol</a>
                            </li>
                        }
                        @if (User.IsInRole("Editor interzis"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Acasa</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Articles" asp-action="Index">Articole</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted d-flex flex-row">
        <div class="container">
            &copy; 2022 - CrowdKnowledgeContribution - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
        <a href="/Home/Contact/" class="text-black" style="margin-right: 50px">Contact us</a>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <!--summernote-->
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/Summernote.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>